

#ifndef _BRACZ_CS_TIVA_HARDWARE_HXX_
#define _BRACZ_CS_TIVA_HARDWARE_HXX_

#define LED_RED GPIO_PORTN_BASE, GPIO_PIN_4
#define LED_YELLOW GPIO_PORTQ_BASE, GPIO_PIN_0
#define LED_GREEN GPIO_PORTP_BASE, GPIO_PIN_4
#define LED_BLUE GPIO_PORTD_BASE, GPIO_PIN_2

#define LED_B1 GPIO_PORTN_BASE, GPIO_PIN_1
#define LED_B2 GPIO_PORTN_BASE, GPIO_PIN_0
#define LED_B3 GPIO_PORTF_BASE, GPIO_PIN_4
#define LED_B4 GPIO_PORTF_BASE, GPIO_PIN_0


#endif // _BRACZ_CS_TIVA_HARDWARE_HXX_
