SUBDIRS = \
	posix.server \
	posix.client \
	freertos.armv7m.ti-launchpad-cc3200 \

#	freertos.armv7m.ek-tm4c123gxl \
#	freertos.armv7m.ek-tm4c1294xl \
#	freertos.armv7m.lpc1768-mbed \
#	linux.x86 \

include $(OPENMRNPATH)/etc/recurse.mk
