SUBDIRS = \
	async_blink \
	blink_raw \
	bootloader \
	bootloader_client \
	clinic_app \
	hub \
	io_board \
	js_hub \
	send_datagram \
	simple_client \
	tractionproxy \
	train \
	usb_can \


include $(OPENMRNPATH)/etc/recurse.mk
