SUBDIRS = linux.x86 mach.x86 mach.x86_64 \
          freertos.armv7m freertos.armv7m.ek-lm4f120xl \
          freertos.armv7m.dk-lm3s9d96 freertos.armv7m.mbed-lpc1768 \
          freertos.armv4t.lpc2368 freertos.armv6m.lpc11cxx \
          #mingw.x86

include $(OPENMRNPATH)/etc/recurse.mk
