SUBDIRS = \
	freertos.armv7m.ek-tm4c123gxl \
	freertos.armv7m.ek-tm4c1294xl \
	freertos.armv7m.lpc1768-mbed \
    freertos.armv7m.st-stm32f303-discovery \
	linux.x86 \


#	freertos.armv7m.bracz-acc \

include $(OPENMRNPATH)/etc/recurse.mk
