-include ../../config.mk
include $(OPENMRNPATH)/etc/path.mk

INCLUDES += -I$(ESPARDUINOPATH)/hardware/esp8266/2.2.0/bootloaders/eboot

export DEFAULT_ADDRESS:=0xDD
include hardware.mk
include $(OPENMRNPATH)/etc/node_id.mk

