export BOARD := BOARD_BRACZ_CS_TIVA
APP_PATH ?= $(realpath ../..)
-include $(APP_PATH)/config.mk
-include $(OPENMRNPATH)/etc/config.mk
LINKCORELIBS = -lnmranet

include hardware.mk
SYSLIBRARIES=
SYSLIB_SUBDIRS=
OBJEXTRA=
