OPENMRNPATH ?= $(realpath ../../..)
include $(OPENMRNPATH)/etc/lib.mk

# To define which subdirectories to build here (specifically when adding
# chip-specific middleware directories), edit
# $(OPENMRNPATH)/src/freertos_drivers/sources.
