SUBDIRS = freertos.mips4k.pic32mx.duinomitemega \
	freertos.armv6m.lpcxpresso-11C24 \
	freertos.armv4t.panda2 \
	freertos.armv7m.mbed-1768 \
	freertos.armv7m.lpc1768-mbed \
	freertos.armv7m.ti-launchpad-lm4f120xl \
	freertos.armv7m.ti-launchpad-tm4c129 \
	freertos.armv7m.st-maple-cmsis \
    freertos.armv7m.st-stm32f303-discovery


include $(OPENMRNPATH)/etc/recurse.mk
