SUBDIRS = freertos.mips4k.pic32mx.duinomitemega \
	freertos.armv6m.lpcxpresso-11C24 \
	freertos.armv7m.mbed-1768 \
	freertos.armv7m.ti-launchpad-lm4f120xl \
	freertos.armv7m.st-maple-cmsis \


include $(OPENMRNPATH)/etc/recurse.mk
