SUBDIRS = \
	bare.armv7m.bracz-acc2 \
	bare.armv7m.bracz-acc3 \
	bare.armv7m.bracz-railcom \
	bare.armv7m.ek-tm4c123gxl \
	nonos.xtensa.esp8266.bracz-deadrail-huzzah \
	nonos.xtensa.esp8266.bracz-deadrail-proto \


include $(OPENMRNPATH)/etc/recurse.mk
