extern const unsigned __attribute__((section("rodata"))) uart1_interrupt_vector_number;
extern const unsigned __attribute__((section("rodata"))) uart2_interrupt_vector_number;
extern const unsigned __attribute__((section("rodata"))) uart3_interrupt_vector_number;
extern const unsigned __attribute__((section("rodata"))) uart4_interrupt_vector_number;
extern const unsigned __attribute__((section("rodata"))) uart5_interrupt_vector_number;
extern const unsigned __attribute__((section("rodata"))) uart6_interrupt_vector_number;
extern const unsigned __attribute__((section("rodata"))) can1_interrupt_vector_number;
extern const unsigned __attribute__((section("rodata"))) can2_interrupt_vector_number;
extern const unsigned __attribute__((section("rodata"))) usb_interrupt_vector_number;
