SUBDIRS = linux.x86 \
    linux.armv7a \
	mach.x86 \
	mach.x86_64 \
	freertos.armv7m.ek-lm4f120xl \
	freertos.armv7m.ek-tm4c123gxl \
	freertos.armv7m.ek-tm4c1294xl \
	freertos.armv7m.mbed-1768 \
	freertos.armv7m.st-maple-cmsis \
    freertos.armv7m.lpc1769-lpcxpresso \
	freertos.armv6m.lpc11cxx \
    freertos.armv6m.st-stm32f072b-discovery \
	freertos.armv4t.panda2 \
	freertos.mips4k.pic32mx-duinomitemega \
	js.emscripten \


include $(OPENMRNPATH)/etc/recurse.mk
