SUBDIRS = linux.x86 \
	freertos.armv7m.ek-lm4f120xl \
	freertos.armv7m.ek-tm4123gxl \
	freertos.armv7m.mbed-1768 \
	freertos.armv7m.st-maple-cmsis \
	freertos.armv6m.lpc11cxx \
	freertos.armv4t.panda2 \
	freertos.mips4k.pic32mx-duinomitemega \


include $(OPENMRNPATH)/etc/recurse.mk
