SUBDIRS = \
	freertos.armv7m.ek-tm4c123gxl \
	freertos.armv7m.ek-tm4c1294xl \
	freertos.armv6m.st-stm32f072b-discovery \
	freertos.armv7m.st-stm32f303-discovery \
    linux.armv7a \
    linux.x86 \
    mach.x86


#	freertos.armv7m.lpc1768-mbed \
#	linux.x86 \

include $(OPENMRNPATH)/etc/recurse.mk
