SUBDIRS = linux.x86 nuttx.armv7m freertos.armv7m freertos.armv7m.mbed-lpc1768 freertos.armv6m freertos.armv4t freertos.mips4k.pic32mx mach.x86 mach.x86_64 #mingw.x86

include $(OPENMRNPATH)/etc/recurse.mk
