SUBDIRS = linux.x86 \
          linux.llvm \
          linux.armv7a \
          freertos.armv7m \
          freertos.armv7m.mbed-lpc1768 \
          freertos.armv6m \
          freertos.armv4t \
          freertos.mips4k.pic32mx \
          mach.x86 mach.x86_64 \
          bare.armv7m \
          js.emscripten \
          mingw.x86 \


          #test
          #nuttx.armv7m \

include $(OPENMRNPATH)/etc/recurse.mk
